class DataExtractionPaths:
    DATA_EXTRACTION_DIR = '../smarthub_beta_data/data_extraction/'
    ENTITY_EXTRACTION_DIR = '../entity_extraction/'

    CHICAGO_ENCYCLOPEDIA_DATA_FILE_NAME = 'chicago_encyclopedia_'
    CHICAGO_ENCYCLOPEDIA_TEXT_DATA_PATH = DATA_EXTRACTION_DIR + 'chicago_encyclopedia_extraction/' + \
        CHICAGO_ENCYCLOPEDIA_DATA_FILE_NAME + 'text.txt'
    CHICAGO_ENCYCLOPEDIA_ENTITY_DATA_PATH = ENTITY_EXTRACTION_DIR + 'chicago_encyclopedia_extraction/' + \
        CHICAGO_ENCYCLOPEDIA_DATA_FILE_NAME + 'ne.txt'
    CHICAGO_ENCYCLOPEDIA_IOB_FILE_NAME = 'chicago_encyclopedia_iob.txt'
    CHICAGO_ENCYCLOPEDIA_IOB_PATH = ENTITY_EXTRACTION_DIR + 'chicago_encyclopedia_extraction/' + \
        CHICAGO_ENCYCLOPEDIA_IOB_FILE_NAME
    CHICAGO_ENCYCLOPEDIA_ENTITIES_FILE_NAME = 'chicago_encyclopedia_entities_manualedit.txt'
    CHICAGO_ENCYCLOPEDIA_ENTITIES_PATH = DATA_EXTRACTION_DIR + 'chicago_encyclopedia_extraction/' + \
        CHICAGO_ENCYCLOPEDIA_ENTITIES_FILE_NAME
    CHICAGO_ENCYCLOPEDIA_TOKENS_FILE_NAME = 'tokenized_' + CHICAGO_ENCYCLOPEDIA_DATA_FILE_NAME + 'text.txt'
    CHICAGO_ENCYCLOPEDIA_TOKENS_FILE_PATH = ENTITY_EXTRACTION_DIR + 'chicago_encyclopedia_extraction/' + \
        CHICAGO_ENCYCLOPEDIA_TOKENS_FILE_NAME

    CHICAGO_SUN_TIMES_NEIGHBORHOODS_DATA_FILE_NAME = 'chicago_sun_times_neighborhoods_'
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_TEXT_DATA_PATH = DATA_EXTRACTION_DIR + \
        'chicago_sun_times_neighborhoods_extraction/' + \
        CHICAGO_SUN_TIMES_NEIGHBORHOODS_DATA_FILE_NAME + 'text.txt'
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_ENTITY_DATA_PATH = ENTITY_EXTRACTION_DIR + \
        'chicago_sun_times_neighborhoods_extraction/' + \
        CHICAGO_SUN_TIMES_NEIGHBORHOODS_DATA_FILE_NAME + 'ne.txt'
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_IOB_FILE_NAME = 'chicago_sun_times_neighborhoods_iob.txt'
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_IOB_PATH = ENTITY_EXTRACTION_DIR + 'chicago_sun_times_neighborhoods_extraction/' + \
        CHICAGO_SUN_TIMES_NEIGHBORHOODS_IOB_FILE_NAME
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_TOKENS_FILE_NAME = 'tokenized_' + CHICAGO_SUN_TIMES_NEIGHBORHOODS_DATA_FILE_NAME + \
                                                       'text.txt'
    CHICAGO_SUN_TIMES_NEIGHBORHOODS_TOKENS_FILE_PATH = ENTITY_EXTRACTION_DIR + \
        'chicago_sun_times_neighborhoods_extraction/' + \
        CHICAGO_SUN_TIMES_NEIGHBORHOODS_TOKENS_FILE_NAME

    CWB_CHICAGO_DATA_FILE_NAME = 'cwb_chicago_'
    CWB_CHICAGO_TEXT_DATA_PATH = DATA_EXTRACTION_DIR + 'cwb_chicago_extraction/' + \
        CWB_CHICAGO_DATA_FILE_NAME + 'text.txt'
    CWB_CHICAGO_ENTITY_DATA_PATH = ENTITY_EXTRACTION_DIR + 'cwb_chicago_extraction/' + \
        CWB_CHICAGO_DATA_FILE_NAME + 'ne.txt'
    CWB_CHICAGO_IOB_FILE_NAME = 'cwb_chicago_iob.txt'
    CWB_CHICAGO_IOB_PATH = ENTITY_EXTRACTION_DIR + 'cwb_chicago_extraction/' + CWB_CHICAGO_IOB_FILE_NAME
    CWB_CHICAGO_TOKENS_FILE_NAME = 'tokenized_' + CWB_CHICAGO_DATA_FILE_NAME + 'text.txt'
    CWB_CHICAGO_TOKENS_FILE_PATH = ENTITY_EXTRACTION_DIR + 'cwb_chicago_extraction/' + CWB_CHICAGO_TOKENS_FILE_NAME

    CJP_NEWS_ARTICLES_DATA_FILE_NAME = 'cjp_news_articles_'
    CJP_NEWS_ARTICLES_TEXT_DATA_PATH = DATA_EXTRACTION_DIR + 'cjp_news_articles_extraction/' + \
        CJP_NEWS_ARTICLES_DATA_FILE_NAME + 'text.txt'
    CJP_NEWS_ARTICLES_ENTITY_DATA_PATH = ENTITY_EXTRACTION_DIR + 'cjp_news_articles_extraction/' + \
        CJP_NEWS_ARTICLES_DATA_FILE_NAME + 'ne.txt'
    CJP_NEWS_ARTICLES_RAW_PATH = '../cjp_article_tagging/cjp_tables/newsarticles_article.csv'
    CJP_NEWS_ARTICLES_IOB_FILE_NAME = 'cjp_news_articles_iob.txt'
    CJP_NEWS_ARTICLES_IOB_PATH = ENTITY_EXTRACTION_DIR + 'cjp_news_articles_extraction/' + \
        CJP_NEWS_ARTICLES_IOB_FILE_NAME
    CJP_NEWS_ARTICLES_TOKENS_FILE_NAME = 'tokenized_' + CJP_NEWS_ARTICLES_DATA_FILE_NAME + 'text.txt'
    CJP_NEWS_ARTICLES_TOKENS_FILE_PATH = ENTITY_EXTRACTION_DIR + 'cjp_news_articles_extraction/' + \
        CJP_NEWS_ARTICLES_TOKENS_FILE_NAME

    WIKIPEDIA_DATA_FILE_NAME = 'wikipedia_'
    WIKIPEDIA_TEXT_DATA_PATH = DATA_EXTRACTION_DIR + 'wikipedia_extraction/' + WIKIPEDIA_DATA_FILE_NAME + 'text.txt'
    WIKIPEDIA_ENTITY_DATA_PATH = ENTITY_EXTRACTION_DIR + 'wikipedia_extraction/' + WIKIPEDIA_DATA_FILE_NAME + 'ne.txt'
    WIKIPEDIA_ENTITIES_FILE_NAME = 'wikipedia_entities.txt'
    WIKIPEDIA_ENTITIES_PATH = DATA_EXTRACTION_DIR + 'wikipedia_extraction/' + WIKIPEDIA_ENTITIES_FILE_NAME
    WIKIPEDIA_IOB_FILE_NAME = 'wikipedia_iob.txt'
    WIKIPEDIA_IOB_PATH = ENTITY_EXTRACTION_DIR + 'wikipedia_extraction/' + WIKIPEDIA_IOB_FILE_NAME
    WIKIPEDIA_TOKENS_FILE_NAME = 'tokenized_' + WIKIPEDIA_DATA_FILE_NAME + 'text.txt'
    WIKIPEDIA_TOKENS_FILE_PATH = ENTITY_EXTRACTION_DIR + 'wikipedia_extraction/' + WIKIPEDIA_TOKENS_FILE_NAME

    CHICAGO_CRIME_ONTOLOGY_FILE_NAME = 'covid_counties_cdc_ontology.json'
    CHICAGO_CRIME_ONTOLOGY_PATH = DATA_EXTRACTION_DIR + 'entities_extraction/' + CHICAGO_CRIME_ONTOLOGY_FILE_NAME
    CHICAGO_CRIME_KNOWLEDGEBASE_FILE_NAME = 'knowledgebase_manualedit_filtered_covid.json'
    # CHICAGO_CRIME_KNOWLEDGEBASE_FILE_NAME = 'knowledgebase.json'
    CHICAGO_CRIME_KNOWLEDGEBASE_PATH = DATA_EXTRACTION_DIR + 'entities_extraction/' + \
        CHICAGO_CRIME_KNOWLEDGEBASE_FILE_NAME

    WIKIPEDIA_XML_DATA_PATH = '../enwiki-latest-pages-articles.xml.bz2'
    WIKIPEDIA_JSON_DATA_PATH = '../enwiki-latest_links.json.gz'
    WIKIPEDIA_INDEX_DIR = '../'
    WIKIPEDIA_INDEX_NAME = 'wikipedia_index'
    WIKIPEDIA_INDEX_PATH = WIKIPEDIA_INDEX_DIR + WIKIPEDIA_INDEX_NAME

    ALL_TEXT_DATA_PATHS = [CHICAGO_ENCYCLOPEDIA_TEXT_DATA_PATH, CHICAGO_SUN_TIMES_NEIGHBORHOODS_TEXT_DATA_PATH,
                           CWB_CHICAGO_TEXT_DATA_PATH, CJP_NEWS_ARTICLES_TEXT_DATA_PATH, WIKIPEDIA_TEXT_DATA_PATH]

    ALL_ENTITY_DATA_PATHS = [CHICAGO_ENCYCLOPEDIA_ENTITY_DATA_PATH, CHICAGO_SUN_TIMES_NEIGHBORHOODS_ENTITY_DATA_PATH,
                             CWB_CHICAGO_ENTITY_DATA_PATH, CJP_NEWS_ARTICLES_ENTITY_DATA_PATH,
                             WIKIPEDIA_ENTITY_DATA_PATH]

    ALL_IOB_PATHS = [CHICAGO_ENCYCLOPEDIA_IOB_PATH, CHICAGO_SUN_TIMES_NEIGHBORHOODS_IOB_PATH,
                     CWB_CHICAGO_IOB_PATH, CJP_NEWS_ARTICLES_IOB_PATH, WIKIPEDIA_IOB_PATH]

    ALL_TOKENIZED_PATHS = [CHICAGO_ENCYCLOPEDIA_TOKENS_FILE_PATH, CHICAGO_SUN_TIMES_NEIGHBORHOODS_TOKENS_FILE_PATH,
                           CWB_CHICAGO_TOKENS_FILE_PATH, CJP_NEWS_ARTICLES_TOKENS_FILE_PATH, WIKIPEDIA_TOKENS_FILE_PATH]
